name: Bug Report
description: Report a bug in the project

body:
  - type: dropdown
    id: affected-packages
    attributes:
      label: Which module(s) are the source of the bug?
      options:
        - gui
        - Don't known / other
        - common
        - core
      multiple: true
    validations:
      required: true

  - type: dropdown
    id: is-regression
    attributes:
      label: Is this a regression?
      options:
        - Yes
        - No
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true

  - type: input
    id: reproduction
    attributes:
      label: Please provide a link to a minimal reproduction of the bug

  - type: textarea
    id: exception-or-error
    attributes:
      label: Please provide the exception or error you saw
      render: true

  - type: textarea
    id: environment
    attributes:
      label: Please provide the environment you discovered this bug in (run Python 3.11.2)
      render: true
      placeholder: |
        Python : 3.9.2
        Package Manager: pipenv 2023.5.19
        OS: linux x64

  - type: textarea
    id: other
    attributes:
      label: Anything else?

